---
title: "0809_Coefficient_Plots"
author: "Poppaea"
date: "2023-09-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
all_bmi_data <- read_dta("all_bmi_results.dta")
```

```{r}
library(dplyr)
```

```{r}
install.packages("ggplot2")
install.packages("gridExtra")
library(ggplot2)
library(gridExtra)
```

```{r}

all_bmi_data$regression <- factor(all_bmi_data$regression, levels = c("phenotypic", "mr_unrel", "mr_unrel_PCs", "mr_wf", "mr_wf_PCs"))

# 2. Merge this mapping into all_bmi_data
mapping_df <- data.frame(
  depvar = c("zNPREG05", "zNPENG05", "zNPLES05", "zNPENG08", "zNPLES08", "zNPREG08", "zNPLES09", "zNPREG09"),
  ExamDescription = c("Grade 5 Numeracy", "Grade 5 English", "Grade 5 Reading",
                      "Grade 8 English", "Grade 8 Reading", "Grade 8 Numeracy",
                      "Grade 9 Reading", "Grade 9 Numeracy")
)

all_bmi_data <- merge(all_bmi_data, mapping_df, by = "depvar", all.x = TRUE)

exam_wise_plot_bmi <- function(exam) {
  # Filtering the data by exam:
  data_for_plot <- all_bmi_data[all_bmi_data$depvar == exam,]
  
  # Getting the descriptive title for the current exam
  descriptive_title <- unique(data_for_plot$ExamDescription.x)
  
  plot <- ggplot(data_for_plot, aes(x = regression, y = coef, color = regression)) +
    geom_point() +
    geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.2) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) + # Add horizontal line at y=0
    theme_minimal() +
    labs(title = paste("Coefficient Plot BMI for", descriptive_title, ""), y = "") +
    theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.text.y = element_text(size = 10),
      plot.title = element_text(size = 14, hjust = 0.5),
      legend.position = "none"
    )
  
  filename <- paste0("bmi_", exam, ".eps")
  ggsave(filename, plot, device = "eps", width = 7, height = 5)
  
  return(plot)
}

# Generating the plots
plots_bmi <- lapply(unique(all_bmi_data$depvar), exam_wise_plot_bmi)

# Printing the plots without the legend
print(plots_bmi)

```



```{r}
legend_plot_bmi <- ggplot(all_bmi_data[all_bmi_data$depvar == unique(all_bmi_data$depvar)[1],], 
                          aes(x = regression, y = coef, color = regression)) +
    geom_point() +
    geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.2) +
    theme_minimal() +
    labs(title = "Legend for Coefficient Plot BMI", y = "") + 
    theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.text.y = element_text(size = 10),
      plot.title = element_text(size = 14, hjust = 0.5),
      legend.position = "right"
    )

# Printing the legend plot
print(legend_plot_bmi)
```

